spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pan?useUnicode=true&characterEncodeing=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 3324
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        max-wait: 6000ms
        min-idle: 4

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

jwt:
  expiration: 864000 #10天 单位秒

file-storage-path: D:/panFile/

owner-total-space-default: 10737418240 #10GB 默认用户存储空间大小(byte)