spring:
  profiles:
    active: dev
jwt:
  requestHeader: Authorization
  tokenHead: Bearer
  secret: panpanpanpanppppppppppanpanpoooooooooooooooooohjforehfrehgrhwpbfweooanpan
  expiration: 86400 #单位秒