spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  mvc:
    async:
      request-timeout: -1
jwt:
  requestHeader: Authorization
  tokenHead: Bearer
  secret: panpanpanpanppppppppppanpanpoooooooooooooooooohjforehfrehgrhwpbfweooanpan
  expiration: 86400 #单位秒
