spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pan?useUnicode=true&characterEncodeing=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 3324
    druid:
      filter:
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 1000
      web-stat-filter:
        enabled: true
        exclusions: /druid/*
      stat-view-servlet:
        enabled: true
        login-username: haylen
        login-password: 3324
        allow: 127.0.0.1
        url-pattern: /druid/*

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

jwt:
  expiration: 864000 #10天 单位秒
  secret: panpanpanpanppppppppppanpanpoooooooooooooooooohjforehfrehgrhwpbfweooanpan

file-storage-path: D:/panFile/

owner-total-space-default: 10737418240 #10GB 默认用户存储空间大小(byte)